{{- $metadataKeys := (list
  "annotations"
  "labels"
  "name"
  "namespace"
) -}}
{{- $specKeys := (list
  "applyNestedSelectors"
  "generators"
  "goTemplateOptions"
  "ignoreApplicationDifferences"
  "preservedFields"
  "strategy"
  "syncPolicy"
  "template"
) -}}

{{- range $id, $_ := .Values.applicationSets -}}
{{- $data := include "build-resource-data" (dict "root" $ "id" $id "data" . "defaults" $.Values.applicationSetDefaults) | fromYaml -}}
{{- if not $data -}}{{- continue -}}{{- end -}}
{{- with $data -}}
{{ tpl (include "build-patchers" (dict "root" $ "path" "files/applicationset-patchers/*.tpl")) . }}
{{- $metadata := include "filter" (dict "data" . "keys" $metadataKeys) | fromYaml }}
{{- $spec := include "filter" (dict "data" . "keys" $specKeys) | fromYaml }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: {{ ternary ($metadata | toYaml | nindent 2) "{}" (not (empty $metadata)) }}
spec: {{ ternary ($spec | toYaml | nindent 2) "" (not (empty $spec)) }}
  goTemplate: true
  templatePatch: |
    {{/* Default the application name to the application's ID (the filename without extension) */ -}}
    {{ "{{- $_ := set . \"id\" .path.basename -}}" }}
    {{ include "application-template" $ | trim | nindent 4 }}
{{- end -}}
{{- end -}}
