{{- range $id, $_ := .Values.applications -}}
{{- if eq . nil -}}{{- continue -}}{{- end -}}
{{- $_ := set . "id" $id }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ tpl (include "application-template" $) . }}
{{- end -}}
