{{- range $id, $_ := .Values.applicationSets }}
{{- with include "build-resource-data" (dict "root" $ "id" $id "data" . "defaults" $.Values.applicationSetDefaults) | fromYaml }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
{{- end }}
{{- end }}
