{{- range $applicationId, $applicationData := .Values.applications -}}
{{- $_ := set . "name" (.name | default $applicationId) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ tpl (include "application-template" $) . }}
{{- end -}}
