{{- $metadataKeys := (list
  "annotations"
  "labels"
  "name"
  "namespace"
) -}}

{{- range $id, $_ := .Values.applicationSets -}}
{{- $data := include "build-resource-data" (dict "root" $ "id" $id "data" . "defaults" $.Values.applicationSetDefaults) | fromYaml -}}
{{- $metadata := include "filter" (dict "data" $data "keys" $metadataKeys) | fromYaml }}
{{- with $data -}}
{{- include "applicationset.patcher.goTemplateOptionsObject" . }}
{{- include "applicationset.patcher.generatorsObject" . }}
{{- include "applicationset.patcher.xGitGenerator" . }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: {{ ternary ($metadata | toYaml | nindent 2) "{}" (not (empty $metadata)) }}
spec:
  {{- if ne .applyNestedSelectors nil }}
  applyNestedSelectors: {{ .applyNestedSelectors }}
  {{- end }}
  generators: {{ ternary (.generators | toYaml | nindent 4) "[]" (not (empty .generators)) }}
  goTemplate: true
  {{- with .goTemplateOptions }}
  goTemplateOptions: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .ignoreApplicationDifferences }}
  ignoreApplicationDifferences: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .preservedFields }}
  preservedFields: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .strategy }}
  strategy: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .syncPolicy }}
  syncPolicy: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .template }}
  template: {{- . | toYaml | nindent 4 }}
  {{- end }}
  templatePatch: |
    {{/* Default the application name to the application's ID (the filename without extension) */ -}}
    {{ "{{- $_ := set . \"id\" .path.basename -}}" }}
    {{ include "application-template" $ | nindent 4 }}
{{- end -}}
{{- end -}}
