{{- range $applicationSetId, $applicationSetData := .Values.applicationSets -}}
{{- if eq $applicationSetData nil -}}{{- continue -}}{{- end -}}
{{- $enabled := ternary $applicationSetData.enabled true (ne $applicationSetData.enabled nil) }}
{{- if not $enabled }}{{- continue }}{{- end }}
{{- $applicationSetData = mustMergeOverwrite (deepCopy $.Values.applicationSetDefaults) (deepCopy $applicationSetData) -}}
{{- $applicationSetData = tpl ($applicationSetData | toYaml) (dict "metadata" $.Values.metadata) | fromYaml -}}
{{- $name := $applicationSetData.name | default $applicationSetId }}
{{- if $applicationSetData.namePrefix }}
{{- $name = printf "%s-%s" $applicationSetData.namePrefix $name }}
{{- end }}
{{- with $applicationSetData -}}
{{- include "applicationset.patcher.goTemplateOptionsObject" . }}
{{- include "applicationset.patcher.namePrefix" . }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $name | quote }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if ne .applyNestedSelectors nil }}
  applyNestedSelectors: {{ .applyNestedSelectors }}
  {{- end }}
  generators: {{ ternary (.generators | toYaml | nindent 4) (list) (not (empty .generators)) }}
  goTemplate: true
  {{- with .goTemplateOptions }}
  goTemplateOptions: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .ignoreApplicationDifferences }}
  ignoreApplicationDifferences: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .preservedFields }}
  preservedFields: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .strategy }}
  strategy: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .syncPolicy }}
  syncPolicy: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .template }}
  template: {{- . | toYaml | nindent 4 }}
  {{- end }}
  templatePatch: |
    {{/* Default the application name to the application's ID (the filename without extension) */ -}}
    {{ "{{- $applicationId := .path.basename -}}" }}
    {{ "{{- $_ := set . \"name\" (.name | default $applicationId) -}}" }}
    {{ include "application-template" $ | nindent 4 }}
{{- end -}}
{{- end -}}
