{{- range $id, $_ := .Values.projects }}
{{- $data := include "give-me-a-name" (dict "root" $ "id" $id "data" . "defaults" $.Values.projectDefaults) | fromYaml }}

{{- $metadata := dict }}
{{- $metadataKeys := list "annotations" "labels" "name" "namespace" "finalizers" }}

{{- $spec := dict -}}
{{- $specKeys := (list
  "permitOnlyProjectScopedClusters"
  "description"
  "sourceRepos"
  "destinations"
  "clusterResourceWhitelist"
  "clusterResourceBlacklist"
  "namespaceResourceBlacklist"
  "namespaceResourceWhitelist"
  "orphanedResources"
  "roles"
  "syncWindows"
  "signatureKeys"
  "sourceNamespaces"
) }}

{{- range $key := $metadataKeys }}
  {{- with get $data $key }}
    {{- $_ := set $metadata $key . }}
  {{- end }}
{{- end }}

{{- range $key := $specKeys }}
  {{- with get $data $key }}
    {{- $_ := set $spec $key . }}
  {{- end }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: {{ ternary ($metadata | toYaml | nindent 2) "{}" (not (empty $metadata)) }}
spec: {{ ternary ($spec | toYaml | nindent 2) "{}" (not (empty $spec)) }}
{{- end }}
