{{- range $id, $_ := .Values.projects }}
{{- $data := include "build-resource-data" (dict "root" $ "id" $id "data" . "defaults" $.Values.projectDefaults) | fromYaml }}

{{- $metadataKeys := (list
  "annotations"
  "labels"
  "name"
  "namespace"
  "finalizers"
) }}
{{- $metadata := include "filter" (dict "data" $data "keys" $metadataKeys) | fromYaml }}

{{- $specKeys := (list
  "permitOnlyProjectScopedClusters"
  "description"
  "sourceRepos"
  "destinations"
  "clusterResourceWhitelist"
  "clusterResourceBlacklist"
  "namespaceResourceBlacklist"
  "namespaceResourceWhitelist"
  "orphanedResources"
  "roles"
  "syncWindows"
  "signatureKeys"
  "sourceNamespaces"
) }}
{{- $spec := include "filter" (dict "data" $data "keys" $specKeys) | fromYaml }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: {{ ternary ($metadata | toYaml | nindent 2) "{}" (not (empty $metadata)) }}
spec: {{ ternary ($spec | toYaml | nindent 2) "{}" (not (empty $spec)) }}
{{- end }}
