{{- range $id, $data := .Values.projects }}
{{- $data = mustMergeOverwrite (deepCopy $.Values.projectDefaults) (deepCopy $data) }}
{{- $data = tpl ($data | toYaml) $.Values | fromYaml -}}
{{- $name := $data.name | default $id }}
{{- if $data.namePrefix }}
{{- $name = printf "%s-%s" $data.namePrefix $name }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  {{- with $data.annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
  name: {{ $name }}
  {{- with $data.namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with $data.finalizers }}
  finalizers: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if ne $data.permitOnlyProjectScopedClusters nil }}
  permitOnlyProjectScopedClusters: {{ $data.permitOnlyProjectScopedClusters }}
  {{- end }}
  {{- with $data.description }}
  description: {{ . | quote }}
  {{- end }}
  {{- with $data.sourceRepos }}
  sourceRepos: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.destinations }}
  destinations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.clusterResourceWhitelist }}
  clusterResourceWhitelist: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.clusterResourceBlacklist }}
  clusterResourceBlacklist: {{- .| toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.namespaceResourceBlacklist }}
  namespaceResourceBlacklist: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.namespaceResourceWhitelist }}
  namespaceResourceWhitelist: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.orphanedResources }}
  orphanedResources: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.roles }}
  roles: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.syncWindows }}
  syncWindows: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.signatureKeys }}
  signatureKeys: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.sourceNamespaces }}
  sourceNamespaces: {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
