{{- $metadataKeys := (list
  "annotations"
  "finalizers"
  "labels"
  "name"
  "namespace"
) -}}
{{- $specKeys := (list
  "limits"
) -}}

{{- range $namespaceId, $namespaceData := .Values.namespaces -}}
{{- $namespaceData = include "build-resource-data" (dict "root" $ "id" $namespaceId "data" $namespaceData "defaults" $.Values.namespaceDefaults) | fromYaml -}}
{{- if not $namespaceData -}}{{- continue -}}{{- end -}}
{{- range $limitRangeId, $limitRangeData := $namespaceData.limitRanges -}}
{{- $limitRangeData := include "build-resource-data" (dict "root" $ "id" $limitRangeId "data" $limitRangeData "defaults" $.Values.limitRangeDefaults) | fromYaml -}}
{{- if not $limitRangeData -}}{{- continue -}}{{- end -}}
{{- $_ := set $limitRangeData "namespace" $namespaceData.name -}}
{{- $metadata := include "filter" (dict "data" $limitRangeData "keys" $metadataKeys) | fromYaml }}
{{- $spec := include "filter" (dict "data" $limitRangeData "keys" $specKeys) | fromYaml }}
---
apiVersion: v1
kind: LimitRange
{{- with $metadata }}
metadata: {{ . | toYaml | nindent 2 }}
  ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ApplicationSet
      name: test
      uid: 82458a96-cd49-4893-9cf8-7cbc3a3c2c1a
    # - apiVersion: v1
    #   blockOwnerDeletion: true
    #   controller: true
    #   kind: Namespace
    #   name: test
    #   uid: 98476060-32d8-4973-b62f-4b1d287e3aed
{{- end -}}
{{- with $spec }}
spec: {{ . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
