{{- range $id, $_ := .Values.namespaces -}}
{{- $data := include "build-resource-data" (dict "root" $ "id" $id "data" . "defaults" $.Values.namespaceDefaults) | fromYaml -}}
{{- $metadata := include "filter" (dict "data" $data "keys" (list "annotations" "labels" "name")) | fromYaml }}
{{- $spec := include "filter" (dict "data" $data "keys" (list "finalizers")) | fromYaml }}
---
apiVersion: v1
kind: Namespace
{{- with $metadata }}
metadata: {{ . | toYaml | nindent 2 }}
{{- end -}}
{{- with $spec }}
spec: {{ . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
