{{- range $id, $data := .Values.namespaces -}}
{{- $data = mustMergeOverwrite (deepCopy $.Values.namespaceDefaults) (deepCopy $data) }}
{{- $data = tpl ($data | toYaml) .Values | fromYaml -}}
{{- $name := $data.name | default $id }}
{{- if $data.namePrefix }}
{{- $name = printf "%s-%s" $data.namePrefix $name }}
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  {{- with $data.annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $data.labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
---
{{- end -}}
