apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
      - git:
          repoURL: git@github.com:tombulled/k8s.git
          revision: HEAD
          files:
            - path: "tenants/*/config.yaml"
          values:
            tenant: "{{.path.basename}}"
            keepMe: |
              {{- $metadata := dict "id" "t1-dev" "type" "dev" }}
              {{- $valid := true }}

              {{- range $key, $val := (dig "deployTo" "matchLabels" dict .) -}}
                {{- if ne (index $metadata $key) $val -}}
                  {{- $valid = false -}}
                {{- end -}}
              {{- end -}}

              {{- range $expression := (dig "deployTo" "matchExpressions" list .) -}}
                {{- $metadataVal := index $metadata $expression.key -}}
                {{- $exists := ne $metadataVal nil -}}

                {{- if eq $expression.operator "In" -}}
                  {{- $in := false -}}
                  {{- range $value := .values -}}
                    {{- if eq $value $metadataVal -}}
                      {{- $in = true -}}
                    {{- end -}}
                  {{- end -}}
                  {{- if not $in -}}
                    {{- $valid = false -}}
                  {{- end -}}
                {{- else if eq $expression.operator "NotIn" -}}
                  {{- range $value := .values -}}
                    {{- if eq $value $metadataVal -}}
                      {{- $valid = false -}}
                    {{- end -}}
                  {{- end -}}
                {{- else if eq $expression.operator "Exists" -}}
                  {{- if not $exists -}}
                    {{- $valid = false -}}
                  {{- end -}}
                {{- else if eq $expression.operator "DoesNotExist" -}}
                  {{- if $exists -}}
                    {{- $valid = false -}}
                  {{- end -}}
                {{- else -}}
                  {{- fail (printf "Invalid operator: %s" $expression.operator) -}}
                {{- end -}}
              {{- end -}}

              {{- $_ := set . "keepMe" $valid }}
        selector:
          matchLabels:
            keepMe: "true"
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: "tenant-{{.values.tenant}}"
    spec:
      project: default
      sources:
        - repoURL: git@github.com:tombulled/k8s.git
          targetRevision: main
          path: charts/tenant
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$k8s/tenants/defaults.yaml"
              - "$k8s/tenants/defaults-type-dev.yaml"
              - "$k8s/tenants/defaults-t1-dev.yaml"
              - "$k8s/tenants/type-all/{{.values.tenant}}/values.yaml"
              - "$k8s/tenants/type-all/{{.values.tenant}}/values-type-dev.yaml"
              - "$k8s/tenants/type-all/{{.values.tenant}}/values-t1-dev.yaml"
              - "$k8s/tenants/type-dev/{{.values.tenant}}/values.yaml"
              - "$k8s/tenants/type-dev/{{.values.tenant}}/values-t1-dev.yaml"
              - "$k8s/tenants/t1-dev/{{.values.tenant}}/values.yaml"
            valuesObject:
              metadata:
                tenant: "{{.values.tenant}}"
                clusterId: t1-dev
                clusterType: dev
        - repoURL: git@github.com:tombulled/k8s.git
          targetRevision: main
          ref: k8s
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
