apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:tombulled/k8s.git
        revision: HEAD
        directories:
          - path: "tenants/*/*"
        values:
          tenant: "{{.path.basename}}"
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: "tenant-{{.values.tenant}}"
    spec:
      project: default
      sources:
        - repoURL: git@github.com:tombulled/k8s.git
          targetRevision: main
          path: charts/tenant
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$k8s/tenants/defaults.yaml"
              - "$k8s/tenants/defaults-type-dev.yaml"
              - "$k8s/tenants/defaults-t1-dev.yaml"
              - "$k8s/tenants/type-all/{{.values.tenant}}/values.yaml"
              - "$k8s/tenants/type-all/{{.values.tenant}}/values-type-dev.yaml"
              - "$k8s/tenants/type-all/{{.values.tenant}}/values-t1-dev.yaml"
              - "$k8s/tenants/type-dev/{{.values.tenant}}/values.yaml"
              - "$k8s/tenants/type-dev/{{.values.tenant}}/values-t1-dev.yaml"
              - "$k8s/tenants/t1-dev/{{.values.tenant}}/values.yaml"
            valuesObject:
              metadata:
                tenant: "{{.values.tenant}}"
                clusterId: t1-dev
                clusterType: dev
        - repoURL: git@github.com:tombulled/k8s.git
          targetRevision: main
          ref: k8s
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
