apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ironic-standalone-operator.fullname" . }}-serving-cert
  labels:
    {{- include "ironic-standalone-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - ironic-standalone-operator-webhook-service.ironic-standalone-operator-system.svc
  - ironic-standalone-operator-webhook-service.ironic-standalone-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "ironic-standalone-operator.fullname" . }}-selfsigned-issuer
  secretName: irso-webhook-server-cert
