apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    # app.kubernetes.io/component: manager
    # app.kubernetes.io/created-by: ironic-standalone-operator
    # app.kubernetes.io/instance: controller-manager
    # app.kubernetes.io/managed-by: kustomize
    # app.kubernetes.io/name: deployment
    # app.kubernetes.io/part-of: ironic-standalone-operator
    # control-plane: controller-manager
    {{- include "ironic-standalone-operator.labels" . | nindent 4 }}
  name: {{ include "ironic-standalone-operator.fullname" . }}-controller-manager
  # namespace: ironic-standalone-operator-system
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # control-plane: controller-manager
      {{- include "ironic-standalone-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- .Values.podAnnotations | toYaml | nindent 8 }}
      labels:
        # control-plane: controller-manager
        {{- include "ironic-standalone-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ironic-standalone-operator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        envFrom:
        - configMapRef:
            name: {{ include "ironic-standalone-operator.fullname" . }}-ironic-standalone-operator-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        # readinessProbe:
        #   httpGet:
        #     path: /readyz
        #     port: 8081
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 128Mi
        #   requests:
        #     cpu: 10m
        #     memory: 64Mi
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: irso-webhook-server-cert
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
