apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "ironic-standalone-operator.labels" . | nindent 4 }}
    # app.kubernetes.io/component: rbac
    # app.kubernetes.io/created-by: ironic-standalone-operator
    # app.kubernetes.io/instance: leader-election-rolebinding
    # app.kubernetes.io/managed-by: kustomize
    # app.kubernetes.io/name: rolebinding
    # app.kubernetes.io/part-of: ironic-standalone-operator
  name: {{ include "ironic-standalone-operator.fullname" . }}-leader-election-rolebinding
  # namespace: ironic-standalone-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ironic-standalone-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "ironic-standalone-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
