# ref: https://k3d.io/stable/usage/configfile/
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster
servers: 1
agents: 1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
