apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:tombulled/k8s.git
      targetRevision: main
      path: charts/tenant
      helm:
        valueFiles:
          - $k8s/values/root/values.yaml
        valuesObject:
          metadata:
            clusterId: t1-dev
            clusterType: dev
    - repoURL: git@github.com:tombulled/k8s.git
      targetRevision: main
      ref: k8s
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
