apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - mergeKey
        generators:
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              directories:
                - path: "tenants/*"
              values:
                tenant: "{{.path.basename}}"
                mergeKey: '{{ $_ := set . "mergeKey" .path.path }}'
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "tenants/*/config.yaml"
              values:
                # tenant: "{{.path.basename}}"
                mergeKey: '{{ $_ := set . "mergeKey" .path.path }}'
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "tenants/*/config-type-dev.yaml"
              values:
                mergeKey: '{{ $_ := set . "mergeKey" .path.path }}'
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "tenants/*/config-t1-dev.yaml"
              values:
                mergeKey: '{{ $_ := set . "mergeKey" .path.path }}'
      selector:
        matchExpressions:
          - key: enabled
            operator: NotIn
            values:
              - "false"
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: "tenant-{{.values.tenant}}"
    spec:
      project: default
      sources:
        - repoURL: git@github.com:tombulled/k8s.git
          targetRevision: main
          path: charts/tenant
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$k8s/tenants/defaults.yaml"
              - "$k8s/tenants/defaults-type-dev.yaml"
              - "$k8s/tenants/defaults-t1-dev.yaml"
              - "$k8s/{{.path.path}}/values.yaml"
              - "$k8s/{{.path.path}}/values-type-dev.yaml"
              - "$k8s/{{.path.path}}/values-t1-dev.yaml"
            valuesObject:
              metadata:
                tenant: "{{.values.tenant}}"
                clusterId: t1-dev
                clusterType: dev
        - repoURL: git@github.com:tombulled/k8s.git
          targetRevision: main
          ref: k8s
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
