apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:tombulled/k8s.git
        revision: HEAD
        files:
          - path: "tenants/*"
        values:
          tenant: '{{.path.filename}}'
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: "tenant-{{.values.tenant}}"
    spec:
      project: default
      destination: {}
