apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:tombulled/k8s.git
        revision: HEAD
        files:
          - path: "tenants/*.yaml"
        values:
          tenant: '{{.path.filename}}'
  goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: "tenant-{{.values.tenant}}"
    spec:
      project: default
      # syncPolicy:
      #   automated:
      #     selfHeal: true
      #   syncOptions:
      #     - CreateNamespace=true
      # # defines from which Git repository to extract the desired Application manifests
      # source:
      #   chart: "{{.chart}}"
      #   # developers may customize app details using JSON files from above repo URL
      #   repoURL: https://github.com/argoproj/argo-cd.git
      #   targetRevision: HEAD
      #   # Path within the repository where Kubernetes manifests are located
      #   path: applicationset/examples/list-generator/guestbook/{{cluster}}
      #   helm:
      #     useCredentials: "{{.useCredentials}}" # This field may NOT be templated, because it is a boolean field
      #   parameters:
      #     - name: "image.tag"
      #       value: "pull-{{head_sha}}"
      #     - name: "{{.name}}"
      #       value: "{{.value}}"
      #     - name: throw-away
      #       value: "{{end}}"
      # destination:
      #   # Only one of name or server may be specified: if both are specified, an error is returned.
      #   #  Name of the cluster (within Argo CD) to deploy to
      #   name: production-cluster # cluster is restricted
      #   #  API Server URL for the cluster
      #   server: "{{.url}}"
      #   # Target namespace in which to deploy the manifests from source
      #   namespace: dev-team-one # namespace is restricted
