apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-merge-generator
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - mergeKey
        generators:
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "apps/*/*/values.yaml"
              values:
                mergeKey: '{{ $_ := set . "mergeKey" .path.path }}'
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "apps/*/*/values-type-dev.yaml"
              values:
                mergeKey: '{{ $_ := set . "mergeKey" .path.path }}'
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "apps/*/*/values-t1-dev.yaml"
              values:
                mergeKey: '{{ $_ := set . "mergeKey" .path.path }}'
      selector:
        matchExpressions:
          - key: enabled
            operator: NotIn
            values:
              - "false"
  goTemplate: true
  template:
    metadata:
      name: 'some-app-{{.path.path}}-{{.path.filename}}-{{.enabled | default "default"}}'
      annotations:
        enabled: "{{.enabled}}"
        namespace: "{{.namespace}}"
    spec:
      project: default
      sources: []
      destination:
        name: in-cluster
        namespace: '{{.namespace | default "default"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
