apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-merge-generator
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - mergeKey
        generators:
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "apps/*/*/values.yaml"
              values:
                mergeKey: "{{ $_ := set . \"mergeKey\" .path.path }}"
                # selector: "{{ }}"
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "apps/*/*/values-type-dev.yaml"
              values:
                mergeKey: "{{ $_ := set . \"mergeKey\" .path.path }}"
          - git:
              repoURL: git@github.com:tombulled/k8s.git
              revision: HEAD
              files:
                - path: "apps/*/*/values-t1-dev.yaml"
              values:
                mergeKey: "{{ $_ := set . \"mergeKey\" .path.path }}"
        selector:
          # matchLabels:
          #   enabled: "true"
          matchExpressions:
            - key: enabled
              operator: In
              values:
                - ""
                - "true"

  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: "some-app"
    spec:
      project: default
      sources: []
      destination:
        name: in-cluster
        namespace: argocd # default # "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
