destination:
  namespace: argocd

sourcesObject:
  main:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.5.0

syncPolicy:
  syncOptionsObject:
    serverSideApply: true
