# defaults: {}

applications:
  foo: # <-- application "id"
    ### metadata ###
    name: foo # <-- defaults to application ID for apps & filename for appset
    namespace: argocd # <-- defaults to argocd? defaults to release namespace?
    deletion:
      cascade: true # <-- defaults to false
      propagationPolicy: foreground # | background # <-- defaults to foreground
    annotations:
      is-cool: "true"
    labels:
      likes-fish: "false"
    ### spec ###
    project: default # <-- defaults to "default"
    destination:
      name: in-cluster # <-- defaults to "in-cluster"
      namespace: foo
    # ignoreDifferences: [] # TODO
    info:
      - name: "Example"
        value: "https://example.com"
    infoObject:
      sourceRepo: "some-repo"
      example: other-example
    revisionHistoryLimit: 0 # <-- defaults to 10
    sourceHydrator:
      drySource:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
        # helm, kustomize, directory, and plugin fields are available here.
        # See the source.helm, source.kustomize, source.directory, and source.plugin sections above for details.
      syncSource:
        targetBranch: env/prod
        path: guestbook-hydrated
    # source: {} # TODO
    # sources: [] # TODO
    syncPolicy:
      syncOptionsObject: # takes precedence
        validate: true