# defaults: {}

applications:
  foo: # <-- application "id"
    ### metadata ###
    name: foo # <-- defaults to application ID for apps & filename for appset
    namespace: argocd # <-- defaults to argocd? defaults to release namespace?
    finalizers:
      - "my-custom-finalizer"
    deletion:
      cascade: true # <-- defaults to false
      propagationPolicy: ~ # foreground # | background # <-- defaults to foreground
    annotations:
      is-cool: "true"
    labels:
      likes-fish: "false"
    ### spec ###
    project: default # <-- defaults to "default"
    destination:
      name: in-cluster # <-- defaults to "in-cluster"
      namespace: foo
    ignoreDifferences:
      # for the specified json pointers
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/replicas
      - kind: ConfigMap
        jqPathExpressions:
          # Example: Ignore changes to a specific key inside a ConfigMap
          - '.data["config.yaml"]'
      # for the specified managedFields managers
      - group: "*"
        kind: "*"
        managedFieldsManagers:
          - kube-controller-manager
        # Name and namespace are optional. If specified, they must match exactly, these are not glob patterns.
        name: my-deployment
        namespace: my-namespace
    info:
      - name: "Example"
        value: "https://example.com"
    infoObject:
      sourceRepo: "some-repo"
      example: other-example
    revisionHistoryLimit: 0 # <-- defaults to 10
    sourceHydrator:
      drySource:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
        # helm, kustomize, directory, and plugin fields are available here.
        # See the source.helm, source.kustomize, source.directory, and source.plugin sections above for details.
      syncSource:
        targetBranch: env/prod
        path: guestbook-hydrated
    source:
      repoURL: https://github.com/argoproj/foo.git
    sources:
      - repoURL: https://github.com/argoproj/foo.git
    sourcesObject:
      main:
        repoURL: https://github.com/argoproj/argocd-example-apps.git # Can point to either a Helm chart repo or a git repo.
        targetRevision: HEAD # For Helm, this refers to the chart version.
        path: guestbook # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
    syncPolicy:
      automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        enabled: true # Enables automated syncing of the application ( true by default ).
        prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
      syncOptions:     # Sync options which modifies sync behavior
      - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
      - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration
      - ApplyOutOfSyncOnly=true # Only sync out-of-sync resources, rather than applying every object in the application
      - SkipDryRunOnMissingResource=true # Allow skip dry run on missing resource
      - Replace=true # Argo CD will use kubectl replace or kubectl create command to apply changes.
      managedNamespaceMetadata: # Sets the metadata for the application namespace. Only valid if CreateNamespace=true (see above), otherwise it's a no-op.
        labels: # The labels to set on the application namespace
          any: label
          you: like
        annotations: # The annotations to set on the application namespace
          the: same
          applies: for
          annotations: on-the-namespace
      # The retry feature is available since v1.7
      retry:
        limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
        backoff:
          duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
          factor: 2 # a factor to multiply the base duration after each failed retry
          maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

      syncOptionsObject: # takes precedence
        validate: true

# applicationSets: {}
