sourcesObject:
  main:
    repoURL: ghcr.io/rajsinghtech/homer-operator/charts
    chart: homer-operator
    targetRevision: v1.1.0
    helm:
      valueFiles:
        - $values/homer-operator/values.yaml
