foo: "test"
clusterType: dev
values: "foo"

input:
  test: "{{ .foo }}"
  namePrefix: tenant
  name: "{{.values.tenant}}"
  sourcesObject:
    main:
      repoURL: git@github.com:tombulled/k8s.git
      targetRevision: main
      path: charts/tenant
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - "$k8s/tenants/defaults.yaml"
          - "$k8s/tenants/defaults-type-{{.clusterType}}.yaml"
          - "$k8s/tenants/defaults-{{.clusterId}}.yaml"
          - "$k8s/{{.path.path}}/values.yaml"
          - "$k8s/{{.path.path}}/values-type-{{.clusterType}}.yaml"
          - "$k8s/{{.path.path}}/values-{{.clusterId}}.yaml"
        valuesObject:
          metadata:
            tenant: "{{.values.tenant}}"
            clusterId: "{{.clusterId}}"
            clusterType: "{{.clusterType}}"
    k8s:
      repoURL: git@github.com:tombulled/k8s.git
      targetRevision: main
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
