defaults:
  project: default
  deletion:
    cascade: true
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sourcesObject:
    values:
      repoURL: git@github.com:tombulled/k8s.git
      targetRevision: main
      ref: values

applications:
  argo-cd:
    destination:
      namespace: argocd
    sourcesObject:
      main:
        repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: 9.4.3
        helm:
          valueFiles:
            - $values/values/argo-cd/values.yaml
    syncPolicy:
      syncOptionsObject:
        serverSideApply: true

  ingress-nginx:
    destination:
      namespace: ingress-nginx
    sourcesObject:
      main:
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.14.3
        chart: ingress-nginx
        helm:
          valueFiles:
            - $values/values/ingress-nginx/values.yaml

applicationSetDefaults:
  generators: []
  template:
    metadata: {}
    spec:
      project: default
      destination: {}

applicationSets:
  core:
    goTemplate: true
    generators:
      - git:
          repoURL: git@github.com:tombulled/k8s.git
          revision: main
          files:
            - path: "apps/*.yaml"
    template:
      spec:
        project: default
    templatePatch: |
      {{- $applicationId := (.path.filename | split ".")._0 -}}
      metadata:
        name: {{ .name | default $applicationId }}
        {{- with .namespace }}
        namespace: {{ . }}
        {{- end -}}
        {{- with .finalizers }}
        finalizers: {{ . | toYaml | nindent 4 }}
        {{- end }}
        {{- with .annotations }}
        annotations: {{- . | toYaml | nindent 4 }}
        {{- end }}
        {{- with .labels }}
        labels: {{- . | toYaml | nindent 4 }}
        {{- end }}
      spec:
        {{- with .destination }}
        destination: {{- . | toYaml | nindent 4 }}
        {{- end -}}
        {{- with .ignoreDifferences }}
        ignoreDifferences: {{- . | toYaml | nindent 4 }}
        {{- end }}
        {{- with .info }}
        info: {{- . | toYaml | nindent 4 }}
        {{- end }}
        {{- with .project }}
        project: {{ . }}
        {{- end -}}
        {{- if ne .revisionHistoryLimit nil }}
        revisionHistoryLimit: {{ .revisionHistoryLimit }}
        {{- end }}
        {{- with .source }}
        source: {{- . | toYaml | nindent 4 }}
        {{- end }}
        {{- with .sourceHydrator }}
        sourceHydrator: {{- . | toYaml | nindent 4}}
        {{- end }}
        {{- with .sources }}
        sources: {{- . | toYaml | nindent 4 }}
        {{- end }}
        {{- with .syncPolicy }}
        syncPolicy: {{- . | toYaml | nindent 4 }}
        {{- end }}
