applicationDefaults:
  project: default
  deletion:
    cascade: true
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sourcesObject:
    values:
      repoURL: git@github.com:tombulled/k8s.git
      targetRevision: main
      ref: values

applicationSetDefaults:
  generators: []
  template:
    metadata: {}
    spec:
      project: default
      destination: {}

applications:
  argo-cd:
    destination:
      namespace: argocd
    sourcesObject:
      main:
        repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: 9.4.3
        helm:
          valueFiles:
            - $values/values/argo-cd/values.yaml
    syncPolicy:
      syncOptionsObject:
        serverSideApply: true

  ingress-nginx:
    destination:
      namespace: ingress-nginx
    sourcesObject:
      main:
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.14.3
        chart: ingress-nginx
        helm:
          valueFiles:
            - $values/values/ingress-nginx/values.yaml

applicationSets:
  core:
    generators:
      - git:
          repoURL: git@github.com:tombulled/k8s.git
          revision: main
          files:
            - path: "apps/*.yaml"
  bar:
    generators:
      - git:
          repoURL: git@github.com:tombulled/k8s.git
          revision: main
          files:
            - path: "apps/*.yaml"
