metadata:
  type: dev
  id: t1-ops

deployTo:
  matchLabels:
    type: dev

  matchExpressions:
    - key: id
      operator: In
      values:
        - t1-ops
    - key: id
      operator: In
      values:
        - t1-dev

    - key: id
      operator: NotIn
      values:
        - t1-dev
    - key: id
      operator: NotIn
      values:
        - t1-ops

    - key: type
      operator: Exists
    - key: foo
      operator: Exists

    - key: foo
      operator: DoesNotExist
    - key: type
      operator: DoesNotExist
