# ingress:
#   enabled: true
#   hosts:
#     - paths:
#         - path: /
#           pathType: ImplementationSpecific

httpRoute:
  enabled: true
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /rabbitmq
