# TODO: Fix ordering of app sources (alphabetical?)

defaults:
  namespace: argocd
  metadata:
    clusterId: ""
    clusterType: ""

applicationDefaults:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  project: default
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptionsObject:
      serverSideApply: true
    sourcesObject:
      main:
        helm:
          ignoreMissingValueFiles: true

applications:
  root:
    sourcesObject:
      main:
        repoURL: https://github.com/tombulled/tenant.git
        targetRevision: main
        path: tenant
        helm:
          valueFiles:
            - $k8s/values/root/values.yaml
            - $k8s/values/root/values-type-{{.metadata.clusterType}}.yaml
            - $k8s/values/root/values-{{.metadata.clusterId}}.yaml
          valuesObject:
            defaults:
              metadata:
                clusterId: "{{.metadata.clusterId}}"
                clusterType: "{{.metadata.clusterType}}"
      k8s:
        repoURL: https://github.com/tombulled/k8s.git
        targetRevision: main
        ref: k8s

applicationSets:
  tenants:
    generatorsObject:
      main:
        x-git:
          repoURL: git@github.com:tombulled/k8s.git
          revision: HEAD
          path: "tenants/*"
          valueFiles:
            - values.yaml
            - values-type-{{.metadata.clusterType}}.yaml
            - values-{{.metadata.clusterId}}.yaml
    defaults:
      enabled: false
      name: "tenant-{{ `{{.id}}` }}"
      sourcesObject:
        main:
          repoURL: git@github.com:tombulled/tenant.git
          targetRevision: main
          path: tenant
          helm:
            valueFiles:
              - "$k8s/tenants/defaults.yaml"
              - "$k8s/tenants/defaults-type-{{.metadata.clusterType}}.yaml"
              - "$k8s/tenants/defaults-{{.metadata.clusterId}}.yaml"
              - "$k8s/tenants/{{ `{{.id}}` }}/values.yaml"
              - "$k8s/tenants/{{ `{{.id}}` }}/values-type-{{.metadata.clusterType}}.yaml"
              - "$k8s/tenants/{{ `{{.id}}` }}/values-{{.metadata.clusterId}}.yaml"
            valuesObject:
              defaults:
                metadata:
                  tenant: "{{ `{{.id}}` }}"
                  clusterId: "{{.metadata.clusterId}}"
                  clusterType: "{{.metadata.clusterType}}"
        k8s:
          repoURL: git@github.com:tombulled/k8s.git
          targetRevision: main
