defaults:
  $metadata:
    clusterId: ""
    clusterType: ""

projectDefaults:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

projects:
  root:
    description: "Root Project"
    sourceRepos:
      - git@github.com:tombulled/k8s.git
      - git@github.com:tombulled/tenant.git
    clusterResourceWhitelist: []
    destinations:
      - name: in-cluster
        namespace: argocd
  tenants:
    description: "Tenants Project"
    sourceRepos:
      - git@github.com:tombulled/k8s.git
      - git@github.com:tombulled/tenant.git
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
    destinations:
      - name: in-cluster
        namespace: "*"

applicationDefaults:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    name: in-cluster
  syncPolicy:
    syncOptionsObject:
      serverSideApply: true
  sourcesObject:
    main:
      helm:
        ignoreMissingValueFiles: true

applications:
  root:
    project: root
    namespace: argocd
    destination:
      namespace: argocd
    sourcesObject:
      main:
        repoURL: git@github.com:tombulled/tenant.git
        targetRevision: main
        path: tenant
        helm:
          valueFiles:
            - $k8s/values/root/values.yaml
            - $k8s/values/root/values-type-{{$metadata.clusterType}}.yaml
            - $k8s/values/root/values-{{$metadata.clusterId}}.yaml
          values: |
            defaults:
              $metadata: {{ $metadata | toJson }}
      k8s:
        repoURL: git@github.com:tombulled/k8s.git
        targetRevision: main
        ref: k8s
    syncPolicy:
      automated:
        enabled: false

xApplicationSets:
  tenants:
    template:
      metadata:
        annotations:
#           path-json: "{{ `{{.path | toJson}}` }}"
          dir: "{{ `{{ index .path.segments 1 }}` }}"
#           nested-dir: "{{ `{{ index .path.basename }}` }}"
#           id: '{{ `{{ .path.segments | rest | join "-" }}` }}'
          path: '{{ `{{ .path.segments | rest | join "/" }}` }}'
#           base-path: '{{ `{{ slice .path.segments 0 2 | join "/" }}` }}'
      spec:
        project: tenants
    generatorsObject:
      main:
        x-git:
          repoURL: git@github.com:tombulled/k8s.git
          revision: HEAD
          directories:
            - path: "tenants/**"
          valueFiles:
            - values.yaml
            - values-type-{{$metadata.clusterType}}.yaml
            - values-{{$metadata.clusterId}}.yaml
#           values:
#             directory: "{{ `{{.path.path}}` }}"
          id: '.path.segments | rest | join "-"'
    defaults:
      $enabled: false
      name: "tenant-{{ `{{$id}}` }}"
#       annotations:
        # directory: "{{ `{{.values.directory}}` }}"
#         path: "{{ `{{.path | toJson}}` }}"
#         segments: "{{ `{{.path.segments}}` }}"

      sourcesObject:
        main:
          repoURL: git@github.com:tombulled/tenant.git
          targetRevision: main
          path: tenant
          helm:
            valueFiles:
              - "$k8s/tenants/defaults.yaml"
              - "$k8s/tenants/defaults-type-{{$metadata.clusterType}}.yaml"
              - "$k8s/tenants/defaults-{{$metadata.clusterId}}.yaml"
              - "$k8s/{{ `{{.path.path}}` }}/values.yaml"
              - "$k8s/{{ `{{.path.path}}` }}/values-type-{{$metadata.clusterType}}.yaml"
              - "$k8s/{{ `{{.path.path}}` }}/values-{{$metadata.clusterId}}.yaml"
            valuesObject:
              defaults:
                $metadata:
                  tenant: "{{ `{{$id}}` }}"
                  clusterId: "{{$metadata.clusterId}}"
                  clusterType: "{{$metadata.clusterType}}"
        k8s:
          repoURL: git@github.com:tombulled/k8s.git
          targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
