applicationDefaults:
  namePrefix: tenant
  sourcesObject:
    main:
      repoURL: git@github.com:tombulled/k8s.git
      targetRevision: main
      path: charts/tenant
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - "$k8s/tenants/defaults.yaml"
          - "$k8s/tenants/defaults-type-{{.metadata.clusterType}}.yaml"
          - "$k8s/tenants/defaults-{{.metadata.clusterId}}.yaml"
          - "$k8s/{{.path.path}}/values.yaml"
          - "$k8s/{{.path.path}}/values-type-{{.metadata.clusterType}}.yaml"
          - "$k8s/{{.path.path}}/values-{{.metadata.clusterId}}.yaml"
        valuesObject:
          common:
            metadata:
              tenant: "{{.values.tenant}}"
              clusterId: "{{.metadata.clusterId}}"
              clusterType: "{{.metadata.clusterType}}"
    k8s:
      repoURL: git@github.com:tombulled/k8s.git
      targetRevision: main
  destination:
    name: in-cluster
    # namespace: "{{.values.tenant}}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

applicationSets:
  tenants:
    generatorsObject:
      main:
        x-git:
          repoURL: git@github.com:tombulled/k8s.git
          revision: HEAD
          path: "tenants/*"
          valueFiles:
            - values.yaml
            - values-type-{{.metadata.clusterType}}.yaml
            - values-{{.metadata.clusterId}}.yaml
          values:
            tenant: '{{ "{{.path.basename}}" }}'
        selector:
          matchExpressions:
            - key: enabled
              operator: NotIn
              values:
                - "false"
