metadata: {}

### <TODO> ###
commonDefaults:
  metadata: {}
  enabled:
  namePrefix:
  namespace:
  name:
  templateSelf:
### </TODO> ###

projectDefaults: {}
projects: {}

namespaceDefaults: {}
# namespaces: {}
namespaces:
  foo: {}
  bar:
    finalizers:
      - foo

applicationDefaults: {}
applications: {}

applicationSetDefaults:
  template:
    metadata: {}
    spec:
      destination: {}
      project: default
applicationSets: {}
