metadata: {}

### <TODO> ###
commonDefaults:
  annotations:
  labels:
  metadata: {}
  enabled:
  namePrefix:
  namespace:
  name:
  templateSelf:
### </TODO> ###

projectDefaults: {}
projects: {}

namespaceDefaults: {}
namespaces: {}

applicationDefaults: {}
applications: {}

applicationSetDefaults:
  template:
    metadata: {}
    spec:
      destination: {}
      project: default
  namePrefix: prefix
applicationSets:
  foo: {}
