applicationExtensions:
  test: |
    {{- $_ := set $ "labels" (dict "test" "test") -}}

applicationDefaults:
  project: default
  destination:
    name: in-cluster

applications:
  gateway-api-crds-2:
    sources:
      - repoURL: git@github.com:tombulled/k8s.git
        path: charts/gateway-api-crds

# applicationSets:
#   foo: {}
