metadata: {}

projectDefaults: {}
projects: {}

namespaceDefaults: {}
namespaces: {}

applicationDefaults: {}
applications: {}

applicationSetDefaults:
  generators: []
  template:
    metadata: {}
    spec:
      destination: {}
applicationSets: {}
