$enabled: true

xApplicationSets:
  gitlab-runners:
    defaults:
      sourcesObject:
        main:
          repoURL: http://charts.gitlab.io/
          chart: gitlab-runner
          targetRevision: 0.92.1
