applicationSets:
  main:
    generators:
      - matrix:
          generators:
            - list:
                elements:
                  - branch: feature/some-feature
                    number: 57
                    head_sha: dlssadasda
                    author: bob
                    tite: some cool PR
            - list:
                elements:
                  - name: 'myapp-{{ "{{.branch}}" }}-{{ "{{.number}}" }}'
