{{- range $applicationId, $application := .Values.applications -}}
{{- $applicationName := .name | default $applicationId -}}
{{- $applicationNamespace := .namespace | default "argocd" -}}
{{- $applicationInfo := (include "applicationInfo" (dict "list" .info "dict" .infoObject) | fromYaml).info -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $applicationName | quote }}
  namespace: {{ $applicationNamespace | quote }}
  {{- if .deletion.cascade }}
  finalizers:
    {{- with .deletion.propagationPolicy }}
    {{- if eq . "foreground" }}
    - resources-finalizer.argocd.argoproj.io
    {{- else if eq . "background" }}
    - resources-finalizer.argocd.argoproj.io/background
    {{- else }}
      {{- fail (printf "Unrecognised deletion propagation policy: '%s'" .) }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  project: {{ .project }}
  destination:
    {{- if .destination.server | quote }}
    server: {{ .destination.server | quote }}
    {{- else if .destination.name }}
    name: {{ .destination.name | quote }}
    {{- else }}
      {{- fail "Target cluster name or server URL must be set" }}
    {{- end }}
    {{- with .namespace }}
    namespace: {{ . | quote }}
    {{- end }}
  {{- if ne .revisionHistoryLimit nil }}
  revisionHistoryLimit: {{ .revisionHistoryLimit }}
  {{- end }}
  {{- with .syncPolicy }}
  syncPolicy: {{- include "syncPolicy" . | nindent 4 }}
  {{- end }}
  {{- with .sourceHydrator }}
  sourceHydrator: {{- . | toYaml | nindent 4}}
  {{- end }}
  {{- with $applicationInfo }}
  info: {{- $applicationInfo | toYaml | nindent 4 }}
  {{- end }}
{{- end -}}
