{{- range $applicationSetId, $applicationSetData := .Values.applicationSets -}}
{{- include "applicationset.patcher.goTemplateOptionsObject" . }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name | default $applicationSetId }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if ne .applyNestedSelectors nil }}
  applyNestedSelectors: {{ .applyNestedSelectors }}
  {{- end }}
  generators: {{ ternary (.generators | toYaml | nindent 4) (list) (not (empty .generators)) }}
  {{- if ne .goTemplate nil }}
  goTemplate: {{ .goTemplate }}
  {{- end }}
  {{- with .goTemplateOptions }}
  goTemplateOptions: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .ignoreApplicationDifferences }}
  ignoreApplicationDifferences: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .preservedFields }}
  preservedFields: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .strategy }}
  strategy: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .syncPolicy }}
  syncPolicy: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .template }}
  template: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .templatePatch }}
  templatePatchACTUAL: |
    {{- . | nindent 4 }}
  {{- end }}
  templatePatch: |
    {{ "{{- $applicationId := (.path.filename | split \".\")._0 -}}" }}
    {{ "{{- $_ := set . \"name\" (.name | default $applicationId) -}}" }}
    {{- $.Files.Get "files/application-template.yaml" | nindent 4 }}
{{- end -}}
