{{- range $applicationId, $application := .Values.applications -}}
{{- $applicationName := .name | default $applicationId -}}
{{- $applicationNamespace := .namespace | default "argocd" -}}
{{- $applicationInfo := (include "applicationInfo" (dict "list" .info "dict" .infoObject) | fromYaml).info -}}
{{- $applicationFinalizers := .finalizers | default list -}}
{{- if .deletion.cascade -}}
  {{- $propagationPolicy := .deletion.propagationPolicy | default "foreground" -}}
  {{- with $propagationPolicy -}}
    {{- if eq . "foreground" -}}
      {{- $applicationFinalizers = append $applicationFinalizers "resources-finalizer.argocd.argoproj.io" -}}
    {{- else if eq . "background" -}}
      {{- $applicationFinalizers = append $applicationFinalizers "resources-finalizer.argocd.argoproj.io/background" -}}
    {{- else -}}
      {{- fail (printf "Unrecognised deletion propagation policy: '%s'" .) -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $applicationName | quote }}
  namespace: {{ $applicationNamespace | quote }}
  {{- with $applicationFinalizers }}
  finalizers: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  project: {{ .project }}
  {{- with .ignoreDifferences }}
  ignoreDifferences: {{- . | toYaml | nindent 4 }}
  {{- end }}
  destination: {{- .destination | toYaml | nindent 4 }}
  {{- if ne .revisionHistoryLimit nil }}
  revisionHistoryLimit: {{ .revisionHistoryLimit }}
  {{- end }}
  {{- with .syncPolicy }}
  syncPolicy: {{- include "syncPolicy" . | nindent 4 }}
  {{- end }}
  {{- with .sourceHydrator }}
  sourceHydrator: {{- . | toYaml | nindent 4}}
  {{- end }}
  {{- with $applicationInfo }}
  info: {{- $applicationInfo | toYaml | nindent 4 }}
  {{- end }}
  TEMP-TEST: {{- (include "patcher.sources" . | fromYaml).sources | toYaml | nindent 4 }}
{{- end -}}
