projects:
  main:
    clusterResourceWhitelist:
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
      - group: rbac.authorization.k8s.io
        kind: ClusterRoleBinding
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration

namespaceDefaults:
  name: ~

namespaces:
  ironic: {}
  capi-operator-system: {} # cluster-api-operator
  capi-system: {} # cluster-api core provider
  capi-kubeadm-bootstrap-system: {} # cluster-api kubeadm bootstrap provider
