projects:
  main:
    clusterResourceWhitelist:
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
      - group: rbac.authorization.k8s.io
        kind: ClusterRoleBinding

namespaces:
  ironic: {}
