projects:
  core:
    description: "Project for Tenant: core"
    finalizers:
      # Finalizer that ensures that project is not deleted until it is not referenced by any application
      - resources-finalizer.argocd.argoproj.io
    sourceRepos:
      - "*" # git@github.com:tombulled/k8s.git?
    destinations:
      - namespace: ingress-nginx
        server: https://kubernetes.default.svc
      - namespace: argocd
        server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceBlacklist: []
    namespaceResourceWhitelist: []
    roles: []
    syncWindows: []
    sourceNamespaces: []

namespaces:
  ingress-nginx: {}

app-of-apps:
  applicationDefaults:
    project: default
    deletion:
      cascade: true
    destination:
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    sourcesObject:
      values:
        repoURL: git@github.com:tombulled/k8s.git
        targetRevision: main
        ref: values

  applicationSetDefaults:
    generators: []
    template:
      metadata: {}
      spec:
        project: default
        destination: {}

  applicationSets:
    core:
      generators:
        - git:
            repoURL: git@github.com:tombulled/k8s.git
            revision: main
            files:
              - path: "apps/*.yaml"
