projects:
  core:
    description: "some desc"

namespaces:
  ingress-nginx: {}

app-of-apps:
  applicationDefaults:
    project: default
    deletion:
      cascade: true
    destination:
      name: in-cluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    sourcesObject:
      values:
        repoURL: git@github.com:tombulled/k8s.git
        targetRevision: main
        ref: values

  applicationSetDefaults:
    generators: []
    template:
      metadata: {}
      spec:
        project: default
        destination: {}

  applicationSets:
    core:
      generators:
        - git:
            repoURL: git@github.com:tombulled/k8s.git
            revision: main
            files:
              - path: "apps/*.yaml"
