common:
  namespace: argocd

projectDefaults:
  name: ~

namespaceDefaults:
  name: ~

projects:
  main:
    destinations:
      - namespace: ingress-nginx
        name: in-cluster
      - namespace: argocd
        name: in-cluster
    clusterResourceWhitelist:
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
      - group: rbac.authorization.k8s.io
        kind: ClusterRoleBinding
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
      - group: networking.k8s.io
        kind: IngressClass
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition

namespaces:
  main: ~
  ingress-nginx: {}

networkPolicyDefaults:
  enabled: false
resourceQuotaDefaults:
  enabled: false
limitRangeDefaults:
  enabled: false
